---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 24h
  chart:
    spec:
      chart: ./production/helm/loki
      version: 3.8.0
      sourceRef:
        kind: GitRepository
        name: loki
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    gateway:
      enabled: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${CERT_CLUSTER_ISSUER}
        hajimari.io/enable: "false"
        hajimari.io/appName: "Loki"
        hajimari.io/group: "Monitoring"
        hajimari.io/icon: math-log
      hosts:
        - &loki loki.${SECRET_DOMAIN}
      tls:
        - secretName: *loki
          hosts:
            - *loki
    loki:
      auth_enabled: false
      storage:
        type: filesystem
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      querier:
        # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
        max_concurrent: 4
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: local-path
    minio:
      enabled: false

    monitoring:
      dashboards:
        enabled: true
      rules:
        enabled: true
      serviceMonitor:
        enabled: true
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
