apiVersion: v1
kind: Endpoints
metadata:
  name: local-node-exporters
  namespace: monitoring
  labels:
    pulsifer.dev/service: node-exporter
subsets:
  - addresses:
      - ip: 10.2.0.20
        nodeName: cloudpi4
      - ip: 10.2.0.23
        nodeName: homepi4-wifi
      - ip: 10.2.0.24
        nodeName: radiopi0
      - ip: 10.2.0.25
        nodeName: blinkypi0
      # - ip: 10.2.0.27
      #   nodeName: screenpi4
      - ip: 10.2.0.28
        nodeName: screenpi4-wifi
      - ip: 100.85.218.119
        nodeName: 800g3-2.pulsifer.ca.beta.tailscale.net
    ports:
      - name: http-metrics
        port: 9100
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: local-node-exporters
  namespace: monitoring
  labels:
    pulsifer.dev/service: node-exporter
    jobLabel: node-exporter
spec:
  type: ExternalName
  externalName: local-node-exporters
  ports:
    - name: http-metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: local-node-exporters
  namespace: monitoring
  labels:
    pulsifer.dev/service: node-exporter
    release: prom-stack
spec:
  jobLabel: jobLabel
  endpoints:
    - port: http-metrics
      interval: 30s
      honorLabels: true
      scheme: http
      path: /metrics
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
    relabelings:
      - action: replace
        sourceLabels:
        - __address__ # or__meta_kubernetes_pod_ip
        targetLabel: instance
      - action: replace
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: node # same with kube_pod_info etc.
  selector:
    matchLabels:
      pulsifer.dev/service: node-exporter
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: local-node-exporters
  namespace: monitoring
  labels:
    pulsifer.dev/service: node-exporter
    release: prom-stack
spec:
  groups:
    - name: local-node-exporters
      rules:
        - alert: PrometheusTargetMissing
          expr: up {endpoint="http-metrics",  namespace="monitoring", service="local-node-exporters"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            message: Prometheus target missing (instance {{ $labels.instance }})
            description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
