---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodes
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/shared/nodes
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
