---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - cluster-issuers
  - local-path-provisioner
  #  - longhorn
  - metallb
  - persistent-volumes.yaml
  - storage-classes.yaml
