---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cilium
      namespace: kube-system
    - name: cert-manager
      namespace: cert-manager
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: core
              version: v1
              kind: Service
              name: ingress-nginx-controller
            patch: |-
              - op: add
                path: /spec/loadBalancerClass
                value: io.cilium/bgp-control-plane
  values:
    controller:
      replicaCount: 1
      extraEnvs:
        - name: TZ
          value: "${TIMEZONE}"
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "lb.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: |-
            ${LB_NGINX}
        externalTrafficPolicy: Cluster
      publishService:
        enabled: true
      ingressClassResource:
        default: false
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: |-
          401,403,404,500,501,502,503
        enable-brotli: "true"
        forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prom-stack
      podAnnotations:
        configmap.reloader.stakater.com/reload: "cloudflare-proxied-networks"
      resources:
        requests:
          cpu: 10m
          memory: 250Mi
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 3.5.0
      replicaCount: 1
      extraEnvs:
        - name: TEMPLATE_NAME
          value: lost-in-space
        - name: SHOW_DETAILS
          value: "false"
  valuesFrom:
    # Cloudflare Networks
    # https://www.cloudflare.com/ips/
    - targetPath: controller.config.proxy-real-ip-cidr
      kind: ConfigMap
      name: cloudflare-proxied-networks
      valuesKey: cloudflare-proxied-networks.txt
