# Fetched on `chezmoi apply` — zsh plugins (pure + friends) + kube prompt + kubectl plugins
".local/share/zsh/plugins/pure":
  type: archive
  url: "https://github.com/sindresorhus/pure/archive/refs/tags/v1.27.1.tar.gz"
  stripComponents: 1

".local/share/zsh/plugins/fzf-tab":
  type: archive
  url: "https://github.com/Aloxaf/fzf-tab/archive/refs/tags/v1.2.0.tar.gz"
  stripComponents: 1

".local/share/zsh/plugins/zsh-autosuggestions":
  type: archive
  url: "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/tags/v0.7.0.tar.gz"
  stripComponents: 1

".local/share/zsh/plugins/zsh-syntax-highlighting":
  type: archive
  url: "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/0.8.0.tar.gz"
  stripComponents: 1

".local/share/zsh/plugins/kube-ps1":
  type: archive
  url: "https://github.com/jonmosco/kube-ps1/archive/refs/tags/v0.9.0.tar.gz"
  stripComponents: 1

