# bootstrap
brew "mise"
brew "git"

# shell and core developer tools
brew "bat"
brew "btop"
brew "cloudflared"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "jq"
brew "neovim"
brew "nvm"
brew "pre-commit"
brew "ripgrep"
brew "ruby"
brew "sd"
brew "uv"
brew "watchman"

# cloud and containers
cask "gcloud-cli"
cask "docker-desktop"

# kubernetes
brew "helm"
brew "k9s"

# terraform
brew "tenv"
brew "terraform-docs"

# ai homies
cask "1password-cli"
cask "claude-code@latest"
brew "opencode"

tap "peonping/tap"
brew "peonping/tap/peon-ping"

# apps and fonts
cask "font-caskaydia-cove-nerd-font"
cask "secretive"
