[settings]
experimental = true
minimum_release_age_excludes = ["claude-code", "codex", "pi", "opencode"]

[tools]
bun = "latest"
helix = "latest"
herdr = "latest"
worktrunk = "latest"

# cloud & k8s tooling
kubectl = "latest"
helm = "latest"
k9s = "latest"
kubecolor = "latest"
kubectx = "latest"
kubens = "latest"
"github:cloudnative-pg/cloudnative-pg" = { version = "latest", exe = "kubectl-cnpg" }
claude-code = "latest"
opencode = "latest"
gh = "latest"
node = "latest"
