import { GitPullRequest, LockKeyhole, Network } from 'lucide-react';
import { ManagedNotice } from '@/components/managed-notice';
import { Badge } from '@/components/ui/badge';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { getReadModel } from '@/lib/read-model';

export default async function SettingsPage() {
  const { catalog, nativeBootTargets } = await getReadModel();
  const exampleMac = '52:54:00:00:00:01';

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-mono text-3xl font-bold lowercase">deployment</h1>
        <p className="font-mono text-muted-foreground">
          immutable catalog and network-facing route facts
        </p>
      </div>

      <ManagedNotice>
        Edit <code>nix/hosts/spore.nix</code> in a pull request to change these
        values. This dashboard cannot mutate desired state.
      </ManagedNotice>

      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <GitPullRequest className="h-5 w-5 text-spore" />
              catalog policy
            </CardTitle>
            <CardDescription>
              validated values generated by the NixOS module
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-5 font-mono text-sm">
            <Setting label="canonical origin">
              <code className="break-all text-spore">
                {catalog.serverOrigin}
              </code>
            </Setting>
            <Setting label="default profile">
              {catalog.defaultProfile ?? 'none'}
            </Setting>
            <Setting label="unknown hosts">
              <Badge
                variant={catalog.allowUnknownHosts ? 'secondary' : 'spore'}
              >
                {catalog.allowUnknownHosts ? 'allowed' : 'denied'}
              </Badge>
            </Setting>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Network className="h-5 w-5 text-spore" />
              public boot routes
            </CardTitle>
            <CardDescription>
              immutable iPXE and signed native-boot adapters
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 font-mono text-xs">
            <code className="block overflow-x-auto rounded-sm bg-muted p-3">
              {catalog.serverOrigin}/api/boot/{exampleMac}
            </code>
            <code className="block overflow-x-auto rounded-sm bg-muted p-3">
              {catalog.serverOrigin}/api/scripts/&lt;path&gt;
            </code>
            {nativeBootTargets.map((target) => (
              <code
                key={target.id}
                className="block overflow-x-auto rounded-sm bg-muted p-3"
              >
                {target.artifactBaseUrl}/&lt;artifact&gt;
              </code>
            ))}
            <p className="flex gap-2 text-sm text-muted-foreground">
              <LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" />
              The management UI, health route, and static assets are limited by
              nginx to loopback and Tailscale clients.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function Setting({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <p className="mb-1 text-xs uppercase tracking-wider text-muted-foreground">
        {label}
      </p>
      <div>{children}</div>
    </div>
  );
}
