---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
annotations:
  configmap.reloader.stakater.com/reload: cloudflared
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/part-of: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/part-of: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2025.9.0
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
          - name: credentials
            mountPath: /etc/cloudflared/credentials.json
            subPath: credentials.json
            readOnly: true
          - name: credentials
            mountPath: /etc/cloudflared/cert.pem
            subPath: cert.pem
            readOnly: true
          - name: config
            mountPath: /etc/cloudflared/config.yaml
            subPath: cloudflared-config.yaml
            readOnly: true
      volumes:
      - name: credentials
        secret:
          # By default, the credentials file will be created under ~/.cloudflared/<tunnel ID>.json
          # when you run `cloudflared tunnel create`. You can move it into a secret by using:
          # ```sh
          # kubectl create secret generic tunnel-credentials \
          # --from-file=credentials.json=/Users/yourusername/.cloudflared/<tunnel ID>.json
          # ```
          secretName: cloudflared
      # Create a config.yaml file from the ConfigMap below.
      - name: config
        configMap:
          name: cloudflared
          items:
          - key: cloudflared-config.yaml
            path: cloudflared-config.yaml
