---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nix-cache
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/apps/folly/nix-cache
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: config
    - name: networking
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
