---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 24h
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    defaultSettings:
      defaultDataPath: /mnt/disks/longhorn
    networkPolicies:
      enabled: true
    persistence:
      defaultClassReplicaCount: 1
    ingress:
      enabled: true
      host: longhorn.${SECRET_DOMAIN}
      tls: true
      tlsSecret: longhorn.${SECRET_DOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: ${CERT_CLUSTER_ISSUER}
