# kubectl apply --kustomize bootstrap
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: bootstrap
resources:
  - flux-self-managed.yaml
  - repositories/git/infra.yaml
  - cluster.yaml
