---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kube-prometheus.yaml
  - grafana-dashboards
  - local-node-exporters.yaml
  - loki.yaml
  - metrics-server.yaml
 # - picow.yaml
  - promtail.yaml
 # - screenpi4.yaml
  - secret.sops.yaml
  - unpoller
  # - signoz.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /spec/interval
        value: 1m0s
      - op: replace
        path: /spec/chart/spec/interval
        value: 5m0s
      - op: replace
        path: /spec/maxHistory
        value: 2
