---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: monitoring
spec:
  interval: 24h
  chart:
    spec:
      chart: signoz
      version: 0.88.1
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    persistence:
      storageClass: local-path
      size: 10Gi
