---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: reloader
  values:
    fullnameOverride: reloader
    reloader:
      podMonitor:
        enabled: false
        namespace: reloader
        netpol:
          enabled: true
