---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - descheduler
  - reloader
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /spec/interval
        value: 5m0s
      - op: replace
        path: /spec/chart/spec/interval
        value: 10m0s
      - op: replace
        path: /spec/maxHistory
        value: 2
      - op: replace
        path: /spec/upgrade
        value: { cleanupOnFail: true, remediation: { retries: 5 } }
