---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - assemblyline.yaml
  - gateway-api.yaml
  - local-path-provisioner.yaml
  - loki.yaml
patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: GitRepository
    patch: |-
      - op: replace
        path: /spec/interval
        value: 24h
