---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/grafana/loki
  ref:
    tag: v3.4.2
  ignore: |
    # exclude all
    /*
    # include loki directory
    !/production/helm/loki
