---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco-exporter
  namespace: falco
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: falco-exporter
      version: 0.12.2
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system
      interval: 1h0m0s
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  values:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prom-stack
    grafanaDashboard:
      enabled: true
      namespace: monitoring
