---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      version: 4.21.3
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system
  values:
    driver:
      kind: modern-bpf
    falco:
      grpc:
        enabled: true
      grpc_output:
        enabled: true
    falcosidekick:
      enabled: true
      webui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ${CERT_CLUSTER_ISSUER}
            hajimari.io/enable: "true"
            hajimari.io/icon: "mdi:bird"
          hosts:
            - host: &host "falco.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: *host
