#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/

hostname: homepi4

ssh_pwauth: false

users:
- name: kiosk
  gecos: kiosk
  shell: /bin/bash
  groups: [adm, audio, cdrom, dialout, dip, plugdev, tty, video]
- name: jawn
  gecos: jawn
  groups: [adm, audio, cdrom, dialout, dip, plugdev, tty, video]
  shell: /bin/bash
  sudo: ALL=(ALL) NOPASSWD:ALL
  ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJewr6lJtffl+uZpnWXTIE5Sd3VeytQRGXKMBv1s5R/v

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
- xserver-xorg
- xinit
- xserver-xorg-legacy

snap:
  commands:
    00: snap install chromium

write_files:
- path: /etc/X11/Xwrapper.config 
  permissions: 0440
  owner: root
  content: |
    allowed_users=anybody
    needs_root_rights=yes
- path: /etc/systemd/system/kiosk.service
  permissions: 0400
  owner: root
  content: |
    [Unit]
    Description=Chrome Kiosk
    Requires=graphical.target
    After=graphical.target

    [Service]
    Environment=DISPLAY=:0.0
    Environment=XAUTHORITY=/home/kiosk/.Xauthority
    ExecStart=xinit /snap/bin/chromium --start-fullscreen --kiosk --incognito --noerrdialogs --disable-translate --no-first-run --fast --fast-start --disable-infobars --disable-features=TranslateUI --disk-cache-dir=/dev/null "https://hub.home.pulsifer.ca" -- -nocursor
    Restart=always
    User=kiosk
    Group=kiosk

    [Install]
    WantedBy=graphical.target

runcmd:
- systemctl daemon-reload
- systemctl enable kiosk

power_state:
 delay: "now"
 mode: reboot
 message: et voila
 timeout: 1
 condition: True
