import { Activity, FileCode, ScrollText, Server } from 'lucide-react';
import Link from 'next/link';
import { ManagedNotice } from '@/components/managed-notice';
import { Badge } from '@/components/ui/badge';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { getReadModel } from '@/lib/read-model';
import { timeAgo } from '@/lib/utils';

export default async function DashboardPage() {
  const model = await getReadModel();
  const observedHosts = model.hosts.filter((host) => host.lastSeen !== null);
  const recentHosts = [...observedHosts]
    .sort((left, right) =>
      (right.lastSeen ?? '').localeCompare(left.lastSeen ?? ''),
    )
    .slice(0, 5);
  const defaultProfile = model.profiles.find((profile) => profile.isDefault);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="font-mono text-3xl font-bold tracking-tight lowercase">
          dashboard
        </h1>
        <p className="font-mono text-muted-foreground">
          read-only network-boot catalog and runtime observations
        </p>
      </div>

      <ManagedNotice />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <SummaryCard
          icon={Server}
          label="configured hosts"
          value={model.hosts.filter((host) => host.configured).length}
          detail={`${observedHosts.length} observed`}
        />
        <SummaryCard
          icon={FileCode}
          label="boot profiles"
          value={model.profiles.length}
          detail={
            defaultProfile ? `default: ${defaultProfile.name}` : 'no default'
          }
        />
        <SummaryCard
          icon={ScrollText}
          label="scripts"
          value={model.scripts.length}
          detail="chainable catalog entries"
        />
        <SummaryCard
          icon={Activity}
          label="boot attempts"
          value={model.hosts.reduce((sum, host) => sum + host.bootCount, 0)}
          detail={
            model.catalog.allowUnknownHosts
              ? 'unknown hosts allowed'
              : 'known hosts only'
          }
        />
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>recent observations</CardTitle>
            <CardDescription>
              latest iPXE requests recorded by Spore
            </CardDescription>
          </CardHeader>
          <CardContent>
            {recentHosts.length === 0 ? (
              <p className="font-mono text-sm text-muted-foreground">
                no boot attempts recorded yet
              </p>
            ) : (
              <div className="divide-y divide-border">
                {recentHosts.map((host) => (
                  <div
                    key={host.macAddress}
                    className="flex flex-col justify-between gap-2 py-3 first:pt-0 sm:flex-row sm:items-center"
                  >
                    <div className="min-w-0">
                      <Link
                        href={`/hosts/${encodeURIComponent(host.macAddress)}`}
                        className="font-mono text-sm text-spore hover:underline"
                      >
                        {host.hostname ?? host.macAddress}
                      </Link>
                      {host.hostname && (
                        <p className="font-mono text-xs text-muted-foreground">
                          {host.macAddress}
                        </p>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge
                        variant={host.configured ? 'secondary' : 'outline'}
                      >
                        {host.configured ? 'configured' : 'observed only'}
                      </Badge>
                      <span className="whitespace-nowrap font-mono text-xs text-muted-foreground">
                        {timeAgo(host.lastSeen)}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            )}
            <Link
              href="/hosts"
              className="mt-4 block font-mono text-sm text-spore hover:underline"
            >
              view all hosts →
            </Link>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>catalog profiles</CardTitle>
            <CardDescription>
              immutable iPXE entry points generated by Nix
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="divide-y divide-border">
              {model.profiles.map((profile) => (
                <div
                  key={profile.id}
                  className="flex items-center justify-between gap-3 py-3 first:pt-0"
                >
                  <div className="min-w-0">
                    <Link
                      href={`/profiles/${encodeURIComponent(profile.id)}`}
                      className="font-mono text-sm text-spore hover:underline"
                    >
                      {profile.name}
                    </Link>
                    <p className="truncate font-mono text-xs text-muted-foreground">
                      {profile.id}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    {profile.isDefault && (
                      <Badge variant="spore">default</Badge>
                    )}
                    <span className="whitespace-nowrap font-mono text-xs text-muted-foreground">
                      {profile.hostCount} host
                      {profile.hostCount === 1 ? '' : 's'}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function SummaryCard({
  icon: Icon,
  label,
  value,
  detail,
}: {
  icon: typeof Server;
  label: string;
  value: number;
  detail: string;
}) {
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 border-0 pb-2">
        <CardTitle className="text-sm">{label}</CardTitle>
        <Icon className="h-4 w-4 text-spore" />
      </CardHeader>
      <CardContent>
        <div className="font-mono text-3xl font-bold text-spore">{value}</div>
        <p className="font-mono text-xs text-muted-foreground">{detail}</p>
      </CardContent>
    </Card>
  );
}
