---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent-sandbox.yaml
  - agents-sandbox-namespace.yaml
  - agents-sandbox-templates.yaml
  - agents-sandbox-claims.yaml
  - agents-sandbox-routes.yaml
  - agents-sandbox-allow-gateway.yaml
