#!/usr/bin/env bash
set -euo pipefail

# Run a shell including the given package from this flake's pinned nixpkgs without updating channels
# Usage: ns <pkg> [-- args]
ns() {
  local pkg="$1"; shift || true
  if [[ -z "$pkg" ]]; then
    echo "usage: ns <pkg> [-- args]" >&2
    exit 1
  fi

  flake_path="$HOME/src/github.com/jonpulsifer/dotfiles"

  if [[ "$(uname)" == "Linux" ]]; then
    if [[ -d "$HOME/src/github.com/jonpulsifer/infra" ]]; then
      flake_path="$HOME/src/github.com/jonpulsifer/infra"
    elif [[ -d "/etc/nixos" ]]; then
      flake_path="/etc/nixos"
    fi
  fi

  nix shell path:$flake_path#''${pkg} -- "$@"
}

ns "$@"
