---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-device
spec:
  rules:
    - # Intel UHD Graphics 630
      name: intel.gpu
      labels:
        intel.feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        # 00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-S GT2 [UHD Graphics 630] [8086:3e92]
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0300"] }
            vendor: { op: In, value: ["8086"] }
            device: { op: In, value: ["3e92"] } # UHD Graphics 630 on riptide
