---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugin-operator
  namespace: nodes
spec:
  interval: 24h
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  dependsOn:
    - name: node-feature-discovery
  values:
    fullnameOverride: intel-device-plugin-operator
  
