---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: nodes
spec:
  interval: 24h
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  values:
    fullnameOverride: node-feature-discovery
