---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k6
  namespace: k6
spec:
  interval: 24h
  chart:
    spec:
      chart: k6-operator
      version: 3.14.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
