---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backups
components:
  - ../../components/restic-backup
resources:
  - namespace.yaml
  - service-account.yaml
  - gcp-credentials.yaml
  - cronjob.yaml
