---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - service-monitor.yaml
namespace: &app unpoller

images:
  - name: ghcr.io/unpoller/unpoller
    newTag: v2.15.3

commonLabels:
  app.kubernetes.io/name: *app
  app.kubernetes.io/part-of: *app

replicas:
  - name: *app
    count: 1
