# Per-cluster OIDC issuer URLs.
#
# Each cluster's kube-apiserver signs SA tokens with the signer key issued in
# pki.tf and advertises issuer https://oidc.lolwtf.ca/<cluster>. The discovery
# documents live in oidc/<cluster>/ here (generated by
# scripts/pki/post-rotate.sh; JWKS kid = kube-apiserver's
# base64url(SHA256(SPKI))) and are served from Cloudflare Pages: the project,
# custom domain, and DNS are Terraform-managed in
# terraform/network/cloudflare/oidc.tf, and .github/workflows/oidc.yml deploys
# the documents on merge to main. Verifiers (GCP Workload Identity Federation,
# the other cluster's structured authentication config) fetch the JWKS there.

locals {
  issuer_base = "https://oidc.lolwtf.ca"
}
