---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../../base/networking/external-dns
  - secret.sops.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: external-dns
    patch: |-
      - op: add
        path: /spec/values/extraArgs/-
        value: --fqdn-template={{ `{{.Name}}.${SECRET_DOMAIN}` }}
