---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 24h
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
    hajimari:
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - argo
          - default
          - vault
          - kube-system
          - monitoring
      name: "overlord"
      customApps:
        - group: Monitoring
          apps:
            - name: ingress (should 404)
              url: http://${METALLB_INGRESS_ADDR}
              icon: test-tube
      globalBookmarks:
        - group: Cloud
          bookmarks:
            - name: GitHub
              url: "https://github.com/jonpulsifer"
            - name: Google Cloud Console
              url: "https://console.cloud.google.com"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: true
          hajimari.io/icon: weather-sunset
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.1.0.0/24,10.2.0.0/24"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
        hosts:
          - host: &hajimari "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *hajimari
            secretName: *hajimari
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
