---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository-metrics-server.yaml
  - metrics-server.yaml
  - helm-repository-vector.yaml
  - vector.yaml
  - helm-repository-open-telemetry.yaml
  - opentelemetry-collector.yaml
  - opentelemetry-collector-servicemonitor.yaml
  - alertmanager-discord.yaml
  - bosun-rules.yaml
  - coredns-rules.yaml
  - etcd-rules.yaml
  - grafana-dashboards
  - helm-repository-grafana.yaml
  - helm-repository-prometheus.yaml
  - helm-repository-victoriametrics.yaml
  - victoria-logs.yaml
