apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dump
  labels:
    app.kubernetes.io/name: nginx-config
    app.kubernetes.io/part-of: dump
data:
  default.conf: |-
    server {
      listen 8080 default_server;
      listen [::]:8080 default_server;
      root /var/lib/dump;
      index index.html;
      location / {
        autoindex on;
        try_files $uri $uri/ =404;
      }
    }
