apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: descheduler
spec:
  interval: 24h
  chart:
    spec:
      chart: descheduler
      version: 0.35.1
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    kind: Deployment
    deschedulingInterval: 30m
    deschedulerPolicy:
      maxNoOfPodsToEvictPerNode: 2
      maxNoOfPodsToEvictPerNamespace: 2
      maxNoOfPodsToEvictTotal: 4
      profiles:
        - name: default
          pluginConfig:
            - name: DefaultEvictor
              args:
                nodeFit: true
                minPodAge: 10m
                noEvictionPolicy: Mandatory
                podProtections:
                  defaultDisabled:
                    - FailedBarePods
                  extraEnabled:
                    - PodsWithPVC
            - name: RemoveFailedPods
              args:
                reasons:
                  - Evicted
                  - NodeShutdown
                includingInitContainers: true
                excludeOwnerKinds:
                  - Job
                minPodLifetimeSeconds: 3600
            - name: PodLifeTime
              args:
                namespaces:
                  exclude:
                    - argo
                    - cert-manager
                    - descheduler
                    - external-secrets
                    - flux-system
                    - kube-system
                    - local-path-provisioner
                    - nodes
                    - tailscale
                maxPodLifeTimeSeconds: 3600
                states:
                  - Pending
                  - PodInitializing
                  - ContainerCreating
                  - ImagePullBackOff
                  - ErrImagePull
                  - ErrImageNeverPull
                  - CreateContainerConfigError
            - name: RemovePodsHavingTooManyRestarts
              args:
                namespaces:
                  exclude:
                    - argo
                    - cert-manager
                    - descheduler
                    - external-secrets
                    - flux-system
                    - kube-system
                    - local-path-provisioner
                    - nodes
                    - tailscale
                podRestartThreshold: 20
                includingInitContainers: true
                states:
                  - CrashLoopBackOff
            - name: RemovePodsViolatingNodeTaints
              args:
                namespaces:
                  exclude:
                    - argo
                    - cert-manager
                    - descheduler
                    - external-secrets
                    - flux-system
                    - kube-system
                    - local-path-provisioner
                    - nodes
                    - tailscale
            - name: RemovePodsViolatingNodeAffinity
              args:
                namespaces:
                  exclude:
                    - argo
                    - cert-manager
                    - descheduler
                    - external-secrets
                    - flux-system
                    - kube-system
                    - local-path-provisioner
                    - nodes
                    - tailscale
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsViolatingInterPodAntiAffinity
              args:
                namespaces:
                  exclude:
                    - argo
                    - cert-manager
                    - descheduler
                    - external-secrets
                    - flux-system
                    - kube-system
                    - local-path-provisioner
                    - nodes
                    - tailscale
            - name: RemoveDuplicates
              args:
                namespaces:
                  exclude:
                    - argo
                    - cert-manager
                    - descheduler
                    - external-secrets
                    - flux-system
                    - kube-system
                    - local-path-provisioner
                    - nodes
                    - tailscale
            - name: RemovePodsViolatingTopologySpreadConstraint
              args:
                namespaces:
                  exclude:
                    - argo
                    - cert-manager
                    - descheduler
                    - external-secrets
                    - flux-system
                    - kube-system
                    - local-path-provisioner
                    - nodes
                    - tailscale
                constraints:
                  - DoNotSchedule
            - name: LowNodeUtilization
              args:
                thresholds:
                  cpu: 35
                  memory: 40
                  pods: 45
                targetThresholds:
                  cpu: 70
                  memory: 70
                  pods: 65
                evictionLimits:
                  node: 1
                evictableNamespaces:
                  exclude:
                    - argo
                    - cert-manager
                    - descheduler
                    - external-secrets
                    - flux-system
                    - kube-system
                    - local-path-provisioner
                    - nodes
                    - tailscale
          plugins:
            deschedule:
              enabled:
                - RemoveFailedPods
                - PodLifeTime
                - RemovePodsHavingTooManyRestarts
                - RemovePodsViolatingNodeTaints
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingInterPodAntiAffinity
            balance:
              enabled:
                - RemoveDuplicates
                - RemovePodsViolatingTopologySpreadConstraint
                - LowNodeUtilization
    service:
      enabled: true
    serviceMonitor:
      enabled: true
