apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Z9JIv52PndE6,iv:E6xZwjTgDU9N9bJjr+RmrLlM+DkoMypu2f3NWKQ1ru8=,tag:qWmdahqe+9U+NgZDvqq+Tg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:LfXqvKPDlmGqelUf4RtySQfjB0U=,iv:I2psHMD5tMH7mmgNffMGa3ACsu7B4BEfdh/os2az6lA=,tag:tULVRzPf/Mb4O4dwr2siRA==,type:str]
    CERT_MANAGER_VAULT_APPROLE_ID: ENC[AES256_GCM,data:PPA/9/OY,iv:aiXEquxzmf03eX2cmS0KwNZU71blgKD1OYm6PlKQcj0=,tag:VpoIyHv6BUXXPLSCSjnD+g==,type:str]
    CERT_MANAGER_VAULT_APPROLE_SECRET: ENC[AES256_GCM,data:ra8tJaKa6g==,iv:Jk5hwtbBMn8cgFu9cw7COjBM6SstT7F+T5Sv2sXVwCg=,tag:5n56QtFxNLDCq8VV4aOQYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSzJCbXFIYWxMNkRiY1VQ
            SWZOdEVtdVpKR0M2TmJEQlRsQkNhSkltVjJnCitoUHllUXJjTEYrOWMveURmY2R3
            YlUzVTNKaVlYRUFnMUdrTk9tbVVYY2sKLS0tIFNkTGdjOHlUZVVKeVBES0hUWDh6
            djYxWS9PWkJXbVVFZSt2QVhyMHgwMUEKjcbkjYKTA30e3lnKd00P0hd5hxor/zHj
            W2PAIE27ptT7n5I5rpp7pzVNKj++1/SAUHSOQxw1QBPGPCJZZevKmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T23:29:28Z"
    mac: ENC[AES256_GCM,data:8DB3F8yARC9f8umBrfVzi9UeA26XNQyIJN/0o8ZBo/U334+Y4o9+SQEffc2/jxg9DCpNR8ud9zTfMTS1f9fG75Uy7FTNYuuIUNXe+7+wfd9KwibEJAgS43sByBjy/i+87MjE0IWO5rYqhLI/vXRNGb+9GNPeeOl/hAuuQtD00Fs=,iv:nT97OAfRCOf1jD6m19GfJCIcQnn+6ihDdQA6xJsCvd0=,tag:6h5G0anOXdIRLtSd0VLhMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
