apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZM7aPgfjFsOD,iv:SxjjgIvyG5M+FRkObr7cwLYWjxYv4FmH72z803NiWLc=,tag:Fy/KQxyWVkNFb7wwpWB2qQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5BFUzQzPf0Djq2Eoeb59fGxa13Y=,iv:q3mkTxMD9NA0bJUYtVsciFs20WR6Xr5G0RH32yIN3p8=,tag:zwTYiofED4/ry+2ls4y0Zw==,type:str]
    CERT_MANAGER_VAULT_APPROLE_ID: ENC[AES256_GCM,data:6JGPP7/33zFgpg==,iv:BACoxxyEYNTmYbiMjjHpf6Yut8TxmdzY7tIcJlx+SlA=,tag:LJRzOKonYpY05+ogEJ1q4g==,type:int]
    CERT_MANAGER_VAULT_APPROLE_SECRET: ENC[AES256_GCM,data:YZHCf6mchQ==,iv:+CzbFfLioncA8mOSBlasMjYzK3JTBjp0HosUP6n7IIE=,tag:cwAvoE9eIZoII9UHDgWTdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWGdZSEFpTVdkeXQzb0NL
            UlNYaUFTcXBlM2pBNmFHNnhNUzVuTkdhckhrCkR1aXJJT0I3dW5NcU5QNG80dG1x
            aVRINGc5RndkYU55NGpzTEZ6bnFIbTQKLS0tIExvRWJjazFHbm5ReE4vMmEzV2lq
            d1VNSDJVcjJTZmdpU2N4aDBXUlgrNUkKlnWTOIuTC0u5OKirsSoFcbeNgsRgcfjU
            OLFolB3wxMCm/IR619NSCJB0np5N5pO+8w2pAJBUSDwpsjdTQK8SRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T22:52:14Z"
    mac: ENC[AES256_GCM,data:mqp9ld54Wctf9AcwlNBL3h+yzLKeZ9Z+FOCXiUrJFJTS5AZ41fIuxuFm+XuuYrBsNaAEcGY7W6TR3A4DtDexr7ARpujMLJ0xiglT/p+XIZuO6JoNTC+CaYphIdKZ19YcKu/q8dWgLzNu9aPyjg+ECNp36ZdmudF/oPn7QPMxays=,iv:rDbKbaLel1j+EWomFPGlJSTWfSEl4t7w6P1Q4yFsV04=,tag:864AiW+s8AIujrlIlWHoAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
