apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Halifax
  API_SERVER_IP: 10.3.0.10
  API_SERVER_PORT: "6443"
  CILIUM_POD_CIDR: 10.100.0.0/16
  BGP_ROUTER_IP: 10.3.0.1/24
  LB_RANGE: 10.3.0.96/28
  LB_NGINX: 10.3.0.100
  CERT_CLUSTER_ISSUER: letsencrypt-production
