apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2zOFxSifvU/Y,iv:otF1Qzf5Dm1x+OOzTszAWe2Yw1jJQ3CcOSK9dDTsdag=,tag:7w8EXLvJuUrePGu4HzfGRw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Pbh2WHQViL3S9atZSmOhcKuDk+A=,iv:4pnp7LuHDkiB+B86Blq0aLAOg64LJTkTQdGpn65E0kc=,tag:9A6pizvRmzcIbNTd72RWbA==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:RoXeLyOG9aIv+Q==,iv:RYxOtaGbttyNNDc/Lwd+OqST+Kej5tWGRpBgtTO88Z4=,tag:sbXE9/Bn0se6YyPasoZPIw==,type:str]
    DID_HALIFAX: ENC[AES256_GCM,data:X8VlF4YD2yOK0A==,iv:FNrG6S+URfHwEGpp68VNqAr0IxkgkboHXQJECRvu6Jw=,tag:uiTiqZcVUbQMaLWQzdI3Hw==,type:str]
    DID_OTTAWA: ENC[AES256_GCM,data:2aGyLJHu+QfMTg==,iv:kIJ5FtzkL5FJnDLCGykQmLkGEdTEYlkVs5Di5/g1Bno=,tag:FD4ZNHRI/LdlHhXThVPXKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRjNiV3JHL2VyM2lzdk03
            ZS9jek43bHJPdjNzVVRIK1pJeDg4VUJsL0I0CmhpbURPNzA2d3ovZmZZN0tsTmF6
            WlhRMUZsU3BQNzJ5clJhQWRXSUt1dEUKLS0tIENqSzlqNklDU3JoVUJUalFzTXdZ
            TWdLUlpKc1V6U3czdzlNeW0rTnhJaGcKpUzn36NjH/Le0bCNCQxel39nqaJJntY7
            VuX6qDr1/qg60tZQwwqriFuPEghZhG8zpt5NvATc4yEJatcJDV+2Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-06T04:37:11Z"
    mac: ENC[AES256_GCM,data:KXk8waajK8f/JvMvsj7OFHTg85+NfZ1yaQrpaEyekGyr4jJ7GkD5Uj3sBdHsBUrgJ8qe9M5N8zecHHqcRve+OVpKDdfWBIYplt7i/Ax4mZ0x0ti+ow4LFN0o1BNzUOZ5N5YleLA472L+M7wPAO7gBAtGYuadORUl0F3cv8l6SRI=,iv:6X+LnnDZk0rYhQk4F/7MlOuLe7PDRr9P7a5m6CkomkA=,tag:snDMNoxieWwu1AVYSFF1fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
