---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hub
  namespace: hub
spec:
  interval: 1h
  chart:
    spec:
      chart: packages/charts/app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  values:
    fullnameOverride: hub
    image: ghcr.io/jonpulsifer/hub:latest@sha256:be4b8826a390ba0a5c72d686ef4f8e0edc2f04f2341f843f7d6f7ff30feba2b0
    command: "bun run start"
    port: 3000
    hostname: hub.lolwtf.ca
    sandbox: false
    env:
      - name: TEMPESTWX_IGNORE_STATIONS
        value: "85191"
    envFromSecret: hub-env
    ingress:
      enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
