---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hub
  namespace: hub
spec:
  interval: 1h
  chart:
    spec:
      chart: packages/charts/app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  values:
    fullnameOverride: hub
    image: ghcr.io/jonpulsifer/hub:latest@sha256:a7bea5c3dd35d2c97b92edca9e8f0a4283815578abb777f473068a24de050086
    command: "bun run start"
    port: 3000
    hostname: hub.lolwtf.ca
    sandbox: false
    env:
      - name: TEMPESTWX_IGNORE_STATIONS
        value: "85191"
      - name: BURNSAFE_COUNTIES
        value: "201806=Colchester,176295=Halifax"
    envFromSecret: hub-env
    ingress:
      enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
