---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hub
  namespace: hub
spec:
  interval: 1h
  chart:
    spec:
      chart: packages/charts/app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  values:
    fullnameOverride: hub
    image: ghcr.io/jonpulsifer/hub:latest@sha256:ccd6da15d68b8139c11988563cc4d0668176dc8a116f8b06edf414b8ae9e29cb
    command: "bun run start"
    port: 3000
    hostname: hub.lolwtf.ca
    sandbox: false
    env:
      - name: TEMPESTWX_IGNORE_STATIONS
        value: "85191"
    envFromSecret: hub-env
    ingress:
      enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
