---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/jonpulsifer/infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/clusters/offsite/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  decryption:
    provider: sops
    secretRef:
      name: sops-age
