apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- if .Values.database.enabled }}
  annotations:
    app.kubernetes.io/database: {{ include "app.databaseName" . }}
    {{- if .Values.database.migration.enabled }}
    app.kubernetes.io/migration: {{ .Values.image }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      {{- if .Values.sandbox }}
      runtimeClassName: gvisor
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - {{ .Values.command | quote }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          {{- if .Values.database.enabled }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.databaseName" . }}-app
                  key: uri
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
