---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/jonpulsifer/infra
