---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/rancher/local-path-provisioner
  ref:
    tag: "v0.0.31"
  ignore: |
    # exclude all
    /*
    # include chart directory
    !/deploy/chart/local-path-provisioner
