---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app podinfo
  namespace: default
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: *app
      version: 6.9.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 1h0m0s
  values:
    nameOverride: *app
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${CERT_CLUSTER_ISSUER}
        hajimari.io/enable: "true"
        hajimari.io/icon: "video-input-antenna"
      hosts:
        - host: &host "podinfo.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    serviceMonitor:
      enabled: true
