apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: external-dns
stringData:
    api-token: ENC[AES256_GCM,data:wnjsE9A2sHzS1ZCcfgZcFaSeKwkQqm2kvP31EZ4NAhwmZMHk8C7+UA==,iv:DqeiqeDlzLKjtWozNNl10EOXU/ahSZ7649NLllXndJM=,tag:evVYBru7cOssIzTZuUioJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSzhFUzBpQ2NxakJWSFA0
            QUcxZGk1a003a1Vxc3VNZHcyYXBrak1sQlhVCjlhbnlnTnVmVk5XME1Ya0RXL0sv
            SW5ISi9NMWdMZlhpdU40S1ZjZU5mbGsKLS0tIG9IUHZhNTNZRGNZalVBdG00VU96
            MllIZ0JaMlRGVGVFZkZsOTRHajVXMzAKuj3EmGW9iUSrVPu+nenAXG2f7Pc9TiD5
            +2OhRni6XjT9zs03rIiNKSPk4NGvX6DcA5pntHilVZED6bj7qrZr/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T22:55:06Z"
    mac: ENC[AES256_GCM,data:YQrjMndk/D/RX4+AJSmPOxwxYZ5P6OYan1TaLlQoVhYIiJEjbFQvXTOXx4oMkGBme7pg9DYhH+X0OTX/LSGzxYH/pMh0O0JGNvTJDyDshNpXxfmdqEJfNm6hteDbiguCJtB8fdO4du93ZZgSF2HmhZNPyR/dU9pUdhsB5m+P+0I=,iv:LPM6XVxrOjyvDGPPk7sVLytw1vwx2mj2X8hrnlP9Ip0=,tag:dGtwg4IAyQ8R/x5p70m4LA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
