apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:9t+U1QNfg5phmm7GSWSFAJUM3Bdh8jXu2j/PqzWv4EmfuGiHiOeqwA==,iv:4ccOYuFprKd2aLWvqa78VDYzHDHm7VBZ5AonCX54ZYo=,tag:0HlyIETtRptKS8j1bu1KpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bWI0WS9qY04ySHgzWDVr
            K3VpZjc5UjBlb0dJMTJCcWszWEJSZmJaNVEwCityWlZqUk1WY0JVblpyRW43ZFlS
            L0ZaRmMzcStHejMza0dFSythNmFQRnMKLS0tIDZXM3VJajFienFWUEpKZUdGVWds
            WXY4Y0toN1R1RkhWL0UyMHJDRWthalUKauIx/5ogMJCyDrH5211rt4xFcDtCr3pt
            Dg5/izSmkxz1CkchlG2TCChFKYkA7HW7htIgxARUIChXz8nfq38xGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T22:52:14Z"
    mac: ENC[AES256_GCM,data:PBzV/TojJWRjNEx/rQDIgMCYMyYiGdn+uNXSwk+Ui3RWayJDCWvTyoLxT41SNKDBmnTDICUtXGk+hy0+1FbJxU9Gece85wCHR09lEplOccRfc3vZkqlVKEc4LNLaE1qQ+xv/YrhLg44FdyknQ0xcPTk7ZC8u7C/t2I/vFJW2Kbc=,iv:bL/Z0NGDkPw1gMaunQCfvd6ZtEoiCP9eAywxVjA2LeQ=,tag:HYnyOac4DwRRXtJ5a5h+Yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
