apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-vault-approle
    namespace: cert-manager
stringData:
    secret: ENC[AES256_GCM,data:2SPkgVYb8Gu1UTg=,iv:kC8JhYCnliSVSzfiwonUnJnVEYx4ZA1DQgHMrEl+VzY=,tag:KffViAG8Pts7E6wORdHKHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWmo3Ym5mUWZvYXNoYTJL
            T3RvcTBLd040d3Fjc29VaVk3Mk9CL1YrcmpRClBtcGsvUmRZUVBuVFRObGVVeW5R
            RGJSZTl6UHF6SjRhT0VCUkFFN2o1bDgKLS0tIERRQ0h2Nk5OMHc0V3laSG9KNTRy
            cmV1TE8xWVBwaGZWNFhicjdaZGVXWnMK93HuRAM2ZU4oTL4Mn3OzecgPHJ0ioPm7
            h74BZ73xKtir4T/PpA/6/1us/A0gv3hnBWsIjHApIbkZ+ZWrGETkVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T22:58:21Z"
    mac: ENC[AES256_GCM,data:fuDy389fb5i6THXXZfx5EfOtdiySN/UqgR3nXRT/XP5nSwi5iGh5ltOUy6FmjyyU5z0aTzJ9Db9K2eUN7A47ib267jfaWgiK4V1rgDpYTi8CmEh9r6E+l2jzXfjG9SlqrX4mBHYlYamF5+fp/TDEe4Hk4Wo3ZSSiecqHsdkrdtk=,iv:U86pXnMFXW5tghVysBxnf2cofN+Vs5w2uWd3VNv2yYY=,tag:BqwGiY3W21dQRTiS6qL8Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
