apiVersion: v1
kind: Endpoints
metadata:
  name: nix-serve
  namespace: nix-cache
  labels:
    app.kubernetes.io/name: nix-serve
    app.kubernetes.io/part-of: nix-cache
subsets:
  - addresses:
      - ip: 10.3.0.13
    ports:
      - port: 5000
