---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: monitoring
spec:
  interval: 1m0s
  maxHistory: 2
  chart:
    spec:
      chart: vector
      version: 0.51.0
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
      interval: 5m0s
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    role: Agent
    tolerations:
      - key: unschedulable
        operator: Equal
        effect: NoSchedule
        value: "true"
    podMonitor:
      enabled: true
    image:
      repository: docker.io/timberio/vector
      tag: 0.55.0-debian
    extraVolumes:
      - name: journal
        hostPath:
          path: /var/log/journal
      - name: machine-id
        hostPath:
          path: /etc/machine-id
    extraVolumeMounts:
      - name: journal
        mountPath: /var/log/journal
        readOnly: true
      - name: machine-id
        mountPath: /etc/machine-id
        readOnly: true
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
        address: 0.0.0.0:8686
      sources:
        kubernetes_logs:
          type: kubernetes_logs
        journald:
          type: journald
          journal_directory: /var/log/journal
      sinks:
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs
          endpoint: http://loki.monitoring.svc.cluster.local:3100
          tenant_id: "1"
          encoding:
            codec: json
          labels:
            job: "kubernetes"
            cluster: "${CLUSTER_NAME}"
            namespace: "{{`{{ kubernetes.pod_namespace }}`}}"
            pod: "{{`{{ kubernetes.pod_name }}`}}"
            container: "{{`{{ kubernetes.container_name }}`}}"
            node: "{{`{{ kubernetes.pod_node_name }}`}}"
        loki_journald:
          type: loki
          inputs:
            - journald
          endpoint: http://loki.monitoring.svc.cluster.local:3100
          tenant_id: "1"
          encoding:
            codec: json
          labels:
            job: "systemd-journal"
            cluster: "${CLUSTER_NAME}"
            host: "{{`{{ host }}`}}"
