#!/usr/bin/env bash
set -eu

# script that uses op run to pass the password from 1password to ssh-add
SSH_KEY_PASSWORD="op://SSH/SSH Key/password"
SSH_KEY_FINGERPRINT="${SSH_KEY_FINGERPRINT:-SHA256:irAaZjbawI58jsAh8EJToey1bV8EA6xIajW8LJWJMi}"
SSH_KEY_PATH="${SSH_KEY_PATH:-$HOME/.ssh/id_ed25519}"

# check if the ssh key exists and is readable and check that the ssh key password and fingerprint are not empty
if [ -r "$SSH_KEY_PATH" ] && [ -n "$SSH_KEY_PASSWORD" ] && [ -n "$SSH_KEY_FINGERPRINT" ]; then
  # check if the ssh key is already added to the ssh agent
  if ! ssh-add -l | grep -q "$SSH_KEY_FINGERPRINT"; then
    echo "$SSH_KEY_PASSWORD" | op inject
  fi
fi
