#!/usr/bin/env python3

import os
import configparser as cp
import sys

if 'CLOUD_SHELL' in os.environ:
    ACTIVE_CONFIG = os.getenv('DEVSHELL_GCLOUD_CONFIG')
else:
    ACTIVE_CONFIG = open(os.environ['CLOUDSDK_CONFIG'] + '/active_config', "r").readlines()[0]

try:
    config_path = os.environ['CLOUDSDK_CONFIG'] + '/configurations/config_' + ACTIVE_CONFIG
    config = cp.ConfigParser()
    config.read(config_path)
    print(config[sys.argv[1]][sys.argv[2]])
except:
    print("")
