apiVersion: v1
kind: Secret
metadata:
  name: rosie
  namespace: rosie
stringData:
  SLACK_CLIENT_SECRET: ENC[AES256_GCM,data:zXeoTkEKrDbsWn/SoJlg9o/1H4cE7MlMszAolyU6aRo=,iv:51+7OLE45LGsxic0LolrYk6Kk1FfDI1iY5J9lsch6mQ=,tag:AaYqUKsOgP45u7VmZvhZ9Q==,type:str]
  SLACK_CLIENT_SIGNING_SECRET: ENC[AES256_GCM,data:bK6WQyhgXJf+rAO73d9SsesOeOHAfr/bV3VRnpC3AKk=,iv:9XVlkVEjT+X7DVtf9iQc/JU+SrIXxCi8Ww2uopE7Gps=,tag:SPLkQcNSu0tDWdHpGJ4gNg==,type:str]
  SLACK_BOT_TOKEN: ENC[AES256_GCM,data:ffLwB4LCWA/DDD06mrXkk3y9awNQbMoe1b36cVDD32i9qffBz6ia/3MihVkbhRninHFAtdVPGPk=,iv:dtvdjposwscplJjUFX3KiqnwVCPFNEaWSSvrx08S3Ys=,tag:ak+Cv1f2n5fa7oqa7xKjaw==,type:str]
  SLACK_APP_TOKEN: ENC[AES256_GCM,data:x5yTqPR/c3qHf+ykazvrA8zScDTUcl20TXh9L05cXNrth7ohBztuRkPeMAhTIMvpYVaewvTRwbN+8wCD5WU3t3PU6pei+/NNAstYZSS1uC1CIciIfzrRnI5++d+8xju9+Q==,iv:lObRrMflMfFyrcJ0xPbTj1rM8lzVw+x1z5BtMlC5Mn4=,tag:zhreqqc9yhHL8CnZ4T5tKw==,type:str]
  PAGERDUTY_TOKEN: ENC[AES256_GCM,data:jTL8eFVSLoDYg3AuHRN8Lz+jFqA=,iv:ux/nY/h64Huv/TAhv2hViqClQf9mW/NE5zSinuT//WE=,tag:TQbQpsTml2LlOYz2fT90Mg==,type:str]
  ARGOCD_USERNAME: ENC[AES256_GCM,data:WBMbW8U=,iv:TXcEZBjJgThF4DSKWJCGw/jPnu2yerT/th4igTyiLeA=,tag:A65CawLUSKC0EVi4cYnMRQ==,type:str]
  ARGOCD_PASSWORD: ENC[AES256_GCM,data:9DwuLb63HGU5wG8rddkg3g==,iv:XENLmCmdAyf03dyTld+U3sTVjsg4kAdHT4Roz8J/vr8=,tag:5TK3iboMbXS8ZIRA9m506w==,type:str]
  ARGOCD_SERVER: ENC[AES256_GCM,data:lW1FtNssfv2ayr+RVeV3PZ5RV04skg==,iv:oudwAChbIARypdSfxOHpb/5GV8M0W9rOqp5Xi3ISSAo=,tag:JBaMscM5KSHr1Xi6gS9PMw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWNhd2JaRXBZVTlCaDFk
        ZkU1R0JFT2IwT1NCMXdyc1M4TXg3ODBtTmpZCkNGVTNaNkZCV2lJSVFRN2h6Q1Yz
        TlAyRDM1eUpRRjQxVWp1VmtXS3RYVU0KLS0tIEdVZGQvZ1lwdEFadTRpM3hBUEtr
        Z3dSb0FOYkVxbExmWmpuNWRhT3d6QVEKuClj9omM1KbHYs2u8eR4I7nul4tHL3PQ
        8rx/j0vEj8JAwTaKEaZONu+B813aAf7tYC1qbIymdcO7fDeJ7BQLbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-10-22T17:29:45Z"
  mac: ENC[AES256_GCM,data:OUC4TnOb4jCvvD1wN88Mi3g1LX8kg8mVZ3RQM2WEuLYHTRLgtf2ZG/wu4SHrr1M6K4wEQJrflg9zTfnrHMZASCmAYL+SL5CZdrNutnDoEqH/p3iTc1cY5giNGNzSGODZZhogp2mFagv8AeT1LxsZjKRxPoBIAwqWCz9EKYgnVbk=,iv:d6xTa1HWjFO89YprVCzeaW41Abk8QgSeyvNlIg0kKK8=,tag:Vzook16soyZcdwY+N3XXmQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.0
