---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: unifi-cert-updater
  namespace: unifi-cert-updater
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: unifi-cert-updater
              image: jonpulsifer/bashcurljq:latest
              envFrom:
                - secretRef:
                    name: unifi-cert-updater
              command:
                - "/bin/bash"
                - "/app/unifi-cert-updater.sh"
              volumeMounts:
                - name: unifi-cert-updater
                  mountPath: /app/unifi-cert-updater.sh
                  subPath: unifi-cert-updater.sh
                  readOnly: true
          volumes:
            - name: unifi-cert-updater
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: unifi-cert-updater
                      items:
                        - key: unifi-cert-updater.sh
                          path: unifi-cert-updater.sh
