---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cron-job.yaml
  - secret.sops.yaml
namespace: unifi-cert-updater
configMapGenerator:
  - name: unifi-cert-updater
    files:
      - unifi-cert-updater.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
