---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner-controller.yaml
  - argo.yaml
  - atlantis.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - descheduler.yaml
  - external-dns.yaml
  - falco.yaml
  - grafana.yaml
  - hajimari.yaml
  - hashicorp.yaml
  - ingress-nginx.yaml
  - intel.yaml
  - jetstack.yaml
  - jonpulsifer.yaml
  - kubernetes-dashboard.yaml
  - longhorn.yaml
  - metrics-server.yaml
  - node-feature-discovery.yaml
  - prometheus.yaml
  - signoz.yaml
  - stakater.yaml
  - stefanprodan.yaml
patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmRepository
    patch: |-
      - op: replace
        path: /spec/interval
        value: 24h
