---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 24h
  chart:
    spec:
      chart: reloader
      version: 2.1.3
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  values:
    fullnameOverride: reloader
    reloader:
      podMonitor:
        enabled: false
        namespace: reloader
        netpol:
          enabled: true
