apiVersion: v1
kind: Secret
metadata:
    name: nix-serve
    namespace: nix-cache
stringData:
    NIX_SERVE_KEY: ENC[AES256_GCM,data:jTGc/t0bLvjKsw7wVfE4emJFpIfpZOZhJkk2vB/0Z6WXvfLOANrD3/r0PJwx2VigxNQu4irC9eKBbGOuXOhayDhX98VF+xGbr3N5Lg4Bm4Kbca3fWzsjCshCORq1l1ftbeC7Ug+9,iv:M7IZusx5/ATXjBqLAG/4mtGxbYDnJo3rxwKdTGyEy/Q=,tag:yXm6Pu16xmlU9hCZgL/vRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaE1ncEdBblY2U0c1REVt
            OEp5OS8vT1M2ZFdmUUU2SHkxckQyemtEU0hBCmtkRUFkN3oyRUo3YWZTdkNiMDd2
            MXRacStPN2xaTFdLb2U2S3JSMlIvQ28KLS0tIDZVUU5hQXBtbVE2K0kzWWdidkNZ
            RnpRU2t5eUZvOTBQUkhHNVE3ZWpwR3MKCgUqWBkMkfUKeHViJVDWoAzRB67H/9Ic
            veU2b7okfWobdc/0I/WfRpUtNE779NLPP94ow/xPNQ+zqKOpyo4pTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T22:09:43Z"
    mac: ENC[AES256_GCM,data:mm5WMgQ2AAXUXnoxqeSKZQjo2AuCf/xwwa5331WVJ3YZZ+vFtGlUoYaCI9tnXzW1iGJzV/jl9CsaDeMTxbaJi51c/QLoRwByue8e+KA+03a6lOlw/l1ZtG7jthwPswEQ6lZ0H0ljIL4lDxFPHQN9buvp4gMnXQRc6C5JTjJx9kQ=,iv:KIKcYJZMrJUHzLVdRRdlalUiJmDtNUoRxn3HKZaq+Cw=,tag:k9G2iCx5chDNgzaetTmXTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
