---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mate
resources:
  - namespace.yaml
  - rbac.yaml
  - sandbox-rbac.yaml
  - external-secret.yaml
  - kthx-sites-secret.yaml
  - network-policy.yaml
  - sandbox-network-policy.yaml
  - deployment.yaml
