import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ManagedNotice } from '@/components/managed-notice';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { getReadModel } from '@/lib/read-model';
import { formatBootPolicy, formatDate } from '@/lib/utils';

interface HostPageProps {
  params: Promise<{ mac: string }>;
}

export default async function HostPage({ params }: HostPageProps) {
  const { mac } = await params;
  const model = await getReadModel();
  const host = model.hosts.find(
    (candidate) =>
      candidate.macAddress === decodeURIComponent(mac).toLowerCase(),
  );

  if (!host) notFound();

  const profile = host.profileId
    ? model.profiles.find((candidate) => candidate.id === host.profileId)
    : undefined;

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button asChild variant="ghost" size="icon">
          <Link href="/hosts" aria-label="Back to hosts">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
        <div className="min-w-0">
          <h1 className="truncate font-mono text-3xl font-bold lowercase">
            {host.hostname ?? 'observed host'}
          </h1>
          <p className="font-mono text-muted-foreground">{host.macAddress}</p>
        </div>
      </div>

      <ManagedNotice>
        {host.configured
          ? 'This host’s name and profile assignment are immutable catalog values generated by Nix.'
          : 'This MAC is not in the Git/Nix catalog; only its runtime observation is stored.'}
      </ManagedNotice>

      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>catalog configuration</CardTitle>
            <CardDescription>
              desired state from the generated boot catalog
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-5 font-mono text-sm">
            <Detail label="source">
              <Badge variant={host.configured ? 'spore' : 'outline'}>
                {host.configured ? 'Git / Nix managed' : 'not configured'}
              </Badge>
            </Detail>
            <Detail label="hostname">{host.hostname ?? '—'}</Detail>
            <Detail label="effective profile">
              {profile ? (
                <Link
                  href={`/profiles/${encodeURIComponent(profile.id)}`}
                  className="text-spore hover:underline"
                >
                  {profile.name} ({profile.id})
                </Link>
              ) : (
                formatBootPolicy(host.effectiveOutcome)
              )}
            </Detail>
            <Detail label="boot URL">
              <code className="block overflow-x-auto rounded-sm bg-muted p-2 text-xs">
                {model.catalog.serverOrigin}/api/boot/{host.macAddress}
              </code>
            </Detail>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>runtime observation</CardTitle>
            <CardDescription>mutable facts recorded in SQLite</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5 font-mono text-sm">
            <Detail label="first seen">{formatDate(host.firstSeen)}</Detail>
            <Detail label="last seen">{formatDate(host.lastSeen)}</Detail>
            <Detail label="boot attempts">{host.bootCount}</Detail>
            <Detail label="last outcome">{host.lastOutcome ?? '—'}</Detail>
            <Detail label="last profile">{host.lastProfile ?? '—'}</Detail>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function Detail({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <p className="mb-1 text-xs uppercase tracking-wider text-muted-foreground">
        {label}
      </p>
      <div>{children}</div>
    </div>
  );
}
