apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nextjs-apps
  namespace: argo
spec:
  generators:
  - list:
      elements:
      - app: request-headers
        server: in-cluster
  template:
    metadata:
      name: "{{app}}"
    spec:
      project: default
      sources:
      - repoURL: 'https://jonpulsifer.github.io/charts'
        chart: nextjs
        targetRevision: 0.0.1
        helm:
          valueFiles:
          - $values/apps/{{app}}/helm/values.yaml
      - repoURL: https://github.com/jonpulsifer/ts.git
        targetRevision: HEAD
        ref: values
      destination:
        name: "{{server}}"
        namespace: "{{app}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
