apiVersion: v1
kind: Secret
metadata:
    name: tronbyt-db
    namespace: tronbyt
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tWhHbk1ICQ==,iv:VuVjWAZ0IARUHVhVF4UUs6CIygmds+qcpUqEle3t+cQ=,tag:G8ivYpoUOWrd3IDFI6gO0w==,type:str]
    password: ENC[AES256_GCM,data:aAq/j2OXcMMFp/U+sldzf7S2P6CvOzKD89uecOq6aGD8DkmQmwCn9w==,iv:5FTX5ltsD92bjOFSlY+QFEehD0TzRlT3kAPj20tWKUY=,tag:b3OnhGdib+5bC50LJ0JWUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bS90LzlPbGJ2bGlmckYw
            YzRRUWZLbkhoekd1eUpBcFNUUFBuZTdkUGxzCmhxSk1sOGlUVnZsMVc3VERIZUda
            RTVqb3pST0N5MDJZa0lOK1JxejQwckEKLS0tIEhqOFJtSW1Kd1dsM09EM1ZVNEZn
            WHhmdlR2aXhqekJ6MG4xTEUrVjdaTVEKjK5Sa9pDlwSbhkhgbzdgPcnWX0fOrTvZ
            nZ6ihdcwjGKgcgUIbm4mXUil9FKcKPGPMEc0Ben2SOnAEwNQ8xI8ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T03:54:40Z"
    mac: ENC[AES256_GCM,data:ggVZgih9wTvyopmiiL3jh0zw0MTwarol8N+oNbH7YM7AslOCLnqNfm8+JwzbD21DjPxf5jZ6Pdpl1wzTSHZbOo2vEvwhWB7bcVyNZjOyReuIfNhvcYFCzAh61T90hMkJtPERH/D7ej/y9UkvKjjtCebIYAatRkznM+DMJsTucrU=,iv:LUvyli13V7qtYnolMP2mWR2jAFLQdsCmk1R5WuhvMww=,tag:iZOoWGZLT5d+D95VZyX3Dw==,type:str]
    version: 3.13.2
