# FML cluster OIDC issuers (oidc.lolwtf.ca): serves the per-cluster discovery
# documents + JWKS generated by terraform/pki (scripts/pki/post-rotate.sh) and
# direct-uploaded by .github/workflows/oidc.yml with `wrangler pages deploy`
# (same CLOUDFLARE_API_TOKEN secret as the wiki). The hostname is load-bearing:
# it is the kube-apiserver --service-account-issuer, appears in every SA token's
# `iss` claim, and is pinned by the GCP workload-identity providers — do not
# rename without a full issuer migration.
resource "cloudflare_pages_project" "oidc" {
  account_id        = local.fml_account_id
  name              = "fml-oidc"
  production_branch = "main"
}

resource "cloudflare_pages_domain" "oidc" {
  account_id   = local.fml_account_id
  project_name = cloudflare_pages_project.oidc.name
  name         = "oidc.${cloudflare_zone.lolwtf_ca.name}"
}

resource "cloudflare_dns_record" "oidc_lolwtf_ca" {
  zone_id = cloudflare_zone.lolwtf_ca.id
  name    = "oidc.lolwtf.ca"
  type    = "CNAME"
  content = cloudflare_pages_project.oidc.subdomain
  proxied = true
  ttl     = 1
}
