# kubectl apply --kustomize bootstrap
# do this after ensuring flux is installed and self managing
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: bootstrap
resources:
  - ../shared/repositories/git/infra.yaml
  - cluster.yaml
