---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
  labels:
    kustomize.toolkit.fluxcd.io/prune: enabled
    lolwtf.ca/sandbox-exec: deny
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
