apiVersion: v1
kind: Secret
metadata:
    name: gateway-ssh
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:rcSJqhIBtw+CW8PVhNRC9VkcAQ==,iv:qOWEgZwfR5JsTxDHXcFozs7P+kgiCAcWjZIGrRSFQ/w=,tag:Zqp1y9nAutRyIgXUY9I9HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUCttSWFXeENvYjA1RFh5
            ZnNmTm80Ty9TZWd2L2Q1a3pMOW8zNG05dTBvCkRIYldUR245RXljZVdjOVJ4VU1T
            enZKcE5qb1VKcDBFV3JkZnlEeWl3TjAKLS0tIGlWQjdhUmcvZ0tyRzhjd0JKbW55
            Y0FzOGUvY0ZBREYyZmNSb1lwWmNjVGMKtExCLGLVYjgJEmYkgKwL+HQpIEqdL4MX
            CwEzjgrkXsLZKWsSARLoa1a/imMsBmOWI9xVaSF8iv32YvO7nb4gNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T20:45:15Z"
    mac: ENC[AES256_GCM,data:Mn8sU/1DwPK+XgNrdejBrEvg+6zcBBBG0ttY1JFNcu+JKFGaLI9tehiPgQhAE2otxkS+RHexuHvlJWp51cC7pQ2kTeCMOcdZcsKqEw2G84xpPcmEaIkp+S+PV4SaNL67yse0Qk3vuKMOXjZY8Xh/aqmmwhp2OBvik/sYak52k7c=,iv:/QtDmV3LU3TKJZbEt21Upya6l+xqZZ2y3i3KX/qkxtg=,tag:P8gIePTsWSJtT+uE7Xe/fg==,type:str]
    version: 3.13.3
