---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spindrift-cloudflared
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: spindrift-cloudflared
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: spindrift cloudflared
        property: password
