{{- if include "kthx-app.serving" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kthx-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kthx-app.labels" . | nindent 4 }}
  annotations:
    {{- include "kthx-app.contractAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kthx-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ include "kthx-app.port" . }}
      targetPort: http
{{- end }}
