---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/arc
  - secret.sops.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/values/maxRunners
        value: 5
