---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: csgo
  namespace: csgo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: csgo
      app.kubernetes.io/part-of: csgo
  serviceName: csgo
  replicas: 1
  minReadySeconds: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csgo
        app.kubernetes.io/part-of: csgo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: steamcmd
        image: cm2network/csgo:latest
        env:
        - name: SRCDS_TOKEN
          valueFrom:
            secretKeyRef:
              name: csgo
              key: SRCDS_TOKEN
        - name: SRCDS_WORKSHOP_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: csgo
              key: SRCDS_WORKSHOP_AUTHKEY
        ports:
        - containerPort: 27015
          name: srcds
        - containerPort: 27020
          name: srctv
        volumeMounts:
        - name: csgo-dedicated
          mountPath: /home/steam/csgo-dedicated/
  volumeClaimTemplates:
  - metadata:
      name: csgo-dedicated
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 20Gi
