#!/usr/bin/env bash
# Generate the per-cluster Flux `cluster-settings` ConfigMaps from the single
# source of truth (topology/topology.json) merged with each cluster's
# hand-edited operational knobs (clusters/<site>/config/cluster-settings.operational.env).
#
#   topology/generate.sh           # (re)write clusters/<site>/config/cluster-settings.yaml
#   topology/generate.sh --check   # exit non-zero if any committed file is stale (CI)
#
# The generated ConfigMaps are committed: Flux reads them at reconcile time via
# `postBuild.substituteFrom` and cannot read topology.json directly. The --check
# mode is the drift guard that keeps the committed copies honest.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOPO="$ROOT/topology/topology.json"

check=0
[ "${1:-}" = "--check" ] && check=1

fail=0
port="$(jq -r '.constants.apiServerPort' "$TOPO")"
native="$(jq -r '.constants.ciliumNativeRoutingCidr' "$TOPO")"

for site in $(jq -r '.clusters | keys[]' "$TOPO"); do
  out="$ROOT/clusters/$site/config/cluster-settings.yaml"
  opsenv="$ROOT/clusters/$site/config/cluster-settings.operational.env"

  if [ ! -f "$opsenv" ]; then
    echo "missing operational env: $opsenv" >&2
    exit 1
  fi
  TIMEZONE=""
  CERT_CLUSTER_ISSUER=""
  # shellcheck disable=SC1090
  source "$opsenv"

  cname="$(jq -r ".clusters.\"$site\".clusterName" "$TOPO")"
  api="$(jq -r ".clusters.\"$site\".apiServerIP" "$TOPO")"
  router="$(jq -r ".clusters.\"$site\".routerIp" "$TOPO")"
  pod="$(jq -r ".clusters.\"$site\".podCidr" "$TOPO")"
  node="$(jq -r ".clusters.\"$site\".nodeCidr" "$TOPO")"
  lb="$(jq -r ".clusters.\"$site\".lbPool" "$TOPO")"

  generated="$(
    cat <<EOF
# GENERATED by topology/generate.sh — DO NOT EDIT.
# Network facts: topology/topology.json. Operational knobs: cluster-settings.operational.env.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # operational (cluster-settings.operational.env)
  TIMEZONE: $TIMEZONE
  CERT_CLUSTER_ISSUER: $CERT_CLUSTER_ISSUER
  # network facts (topology/topology.json)
  CLUSTER_NAME: $cname
  API_SERVER_IP: $api
  API_SERVER_PORT: "$port"
  CILIUM_NATIVE_ROUTING_CIDR: $native
  CILIUM_POD_CIDR: $pod
  K8S_NODE_CIDR: $node
  BGP_ROUTER_IP: $router
  LB_RANGE: $lb
EOF
  )"

  if [ "$check" = 1 ]; then
    if ! diff -u "$out" <(printf '%s\n' "$generated") >/tmp/topo-diff.$$ 2>&1; then
      echo "stale: $out (run topology/generate.sh)" >&2
      cat /tmp/topo-diff.$$ >&2
      fail=1
    fi
    rm -f /tmp/topo-diff.$$
  else
    printf '%s\n' "$generated" >"$out"
    echo "wrote $out"
  fi
done

exit "$fail"
