#!/usr/bin/env bash
# Generate the per-cluster Flux `cluster-topology` ConfigMaps from the single
# source of truth (topology/topology.json).
#
#   topology/generate.sh           # (re)write clusters/<site>/config/cluster-topology.yaml
#   topology/generate.sh --check   # exit non-zero if any committed file is stale (CI)
#
# Each generated ConfigMap carries two views of the same facts:
#
#   * data."topology.json" — the source of truth verbatim (minus its editor-only
#     "$schema" pointer). Portable: mount it as a file, or read the whole document
#     with `kubectl get cm cluster-topology -n flux-system \
#       -o jsonpath='{.data.topology\.json}' | jq`.
#   * flat KEY: value pairs — the local cluster's facts, flattened for Flux
#     `postBuild.substituteFrom` (which performs ${VAR} substitution and cannot
#     read a JSON blob).
#
# The ConfigMaps are committed because Flux reads them at reconcile time and
# cannot read topology.json directly; `--check` is the drift guard that keeps the
# committed copies honest. Operational (non-network) knobs — timezone, cert
# issuer — live in the hand-edited clusters/<site>/config/cluster-settings.yaml
# ConfigMap and are intentionally NOT generated here.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOPO="$ROOT/topology/topology.json"

check=0
[ "${1:-}" = "--check" ] && check=1

fail=0
port="$(jq -r '.constants.apiServerPort' "$TOPO")"
native="$(jq -r '.constants.ciliumNativeRoutingCidr' "$TOPO")"

# The source of truth verbatim, minus the "$schema" editor pointer (a relative
# path that is meaningless in-cluster and whose '$' would otherwise be a landmine
# for any envsubst pass), re-indented to nest under the `topology.json: |` block.
topo_block="$(jq 'del(."$schema")' "$TOPO" | sed 's/^/    /')"

for site in $(jq -r '.clusters | keys[]' "$TOPO"); do
  out="$ROOT/clusters/$site/config/cluster-topology.yaml"

  cname="$(jq -r ".clusters.\"$site\".clusterName" "$TOPO")"
  api="$(jq -r ".clusters.\"$site\".apiServerIP" "$TOPO")"
  router="$(jq -r ".clusters.\"$site\".routerIp" "$TOPO")"
  pod="$(jq -r ".clusters.\"$site\".podCidr" "$TOPO")"
  node="$(jq -r ".clusters.\"$site\".nodeCidr" "$TOPO")"
  lb="$(jq -r ".clusters.\"$site\".lbPool" "$TOPO")"

  generated="$(
    cat <<EOF
# GENERATED by topology/generate.sh — DO NOT EDIT.
# Source of truth: topology/topology.json. Re-run topology/generate.sh after edits.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-topology
  namespace: flux-system
data:
  # The single source of truth, verbatim — portable JSON for any consumer.
  topology.json: |
$topo_block
  # Local cluster network facts, flattened for Flux postBuild.substituteFrom.
  CLUSTER_NAME: $cname
  API_SERVER_IP: $api
  API_SERVER_PORT: "$port"
  CILIUM_NATIVE_ROUTING_CIDR: $native
  CILIUM_POD_CIDR: $pod
  K8S_NODE_CIDR: $node
  BGP_ROUTER_IP: $router
  LB_RANGE: $lb
EOF
  )"

  if [ "$check" = 1 ]; then
    if ! diff -u "$out" <(printf '%s\n' "$generated") >/tmp/topo-diff.$$ 2>&1; then
      echo "stale: $out (run topology/generate.sh)" >&2
      cat /tmp/topo-diff.$$ >&2
      fail=1
    fi
    rm -f /tmp/topo-diff.$$
  else
    printf '%s\n' "$generated" >"$out"
    echo "wrote $out"
  fi
done

exit "$fail"
