---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spindrift-target-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    resourceNames:
      - spindrift-apps
    verbs:
      - get
  - apiGroups:
      - external-secrets.io
    resources:
      - clustersecretstores
    verbs:
      - get
      - list
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spindrift-target-delivery
  namespace: spindrift-apps
rules:
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - events
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spindrift-target-chart-source
  namespace: flux-system
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - gitrepositories
    resourceNames:
      - infra
    verbs:
      - get
