---
apiVersion: v1
kind: Namespace
metadata:
  name: k6
  labels:
    kustomize.toolkit.fluxcd.io/prune: enabled
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: k6
    meta.helm.sh/release-namespace: k6
