apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: dump-gateway
  namespace: dump
  annotations:
    cert-manager.io/cluster-issuer: ${CERT_CLUSTER_ISSUER}
spec:
  gatewayClassName: cilium
  listeners:
    - name: http-gateway
      protocol: HTTP
      port: 80
      hostname: &hostname "dump.${SECRET_DOMAIN}"
    - name: tls-gateway
      protocol: HTTPS
      port: 443
      hostname: *hostname
      tls:
        certificateRefs:
          - kind: Secret
            name: *hostname
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: dump-http-route
  namespace: dump
spec:
  parentRefs:
    - name: dump-gateway
  hostnames:
    - "dump.${SECRET_DOMAIN}"
  rules:
    - backendRefs:
        - name: dump
          port: 8080
