---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 24h
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner
      version: 0.0.30
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    storageClass:
      create: true
      defaultClass: true
      name: local-path
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /mnt/disks
