---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: 46xuydwpk5vbw2gld2pzn5o4pq
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: 46xuydwpk5vbw2gld2pzn5o4pq
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: 46xuydwpk5vbw2gld2pzn5o4pq
        property: cookie-secret
