---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smiirl-data
  namespace: smiirl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
