---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium-preflight
  namespace: kube-system
  labels:
    source.toolkit.fluxcd.io/kind: OCIRepository
spec:
  interval: 24h
  maxHistory: 2
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    timeout: 10m
    remediation:
      retries: 5
  values:
    agent: false
    config:
      enabled: false
    operator:
      enabled: false
    preflight:
      enabled: true
