apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-agent.fullname" . }}-agent-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
{{- if not .Values.secrets }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-agent.fullname" . }}-agent-workspace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
{{- end }}
