---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo
  # - assemblyline
  - cert-manager
  - cilium
  - cloudflare-ddns
  # - datadog
  - default
  - external-dns
  - flux-system
  - ingress-nginx
  - kubernetes-dashboard
  - local-path-provisioner
  # - longhorn
  - monitoring
  - satisfactory
  - vault
  - persistent-volumes.yaml
  - storage-classes.yaml
  - unpoller
