---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc
  - argo
  # - assemblyline
  - cloudnative-pg
  - csgo
  - default
  - descheduler
  # - dump
  # - falco
  - flux-system
  # - minecraft
  - reloader
  - rosie
  - satisfactory
  - vault
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /spec/interval
        value: 5m0s
      - op: replace
        path: /spec/chart/spec/interval
        value: 10m0s
      - op: replace
        path: /spec/maxHistory
        value: 2
      - op: replace
        path: /spec/install
        value: { createNamespace: true, remediation: { retries: 5 } }
      - op: replace
        path: /spec/upgrade
        value: { cleanupOnFail: true, remediation: { retries: 5 } }
