---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - assemblyline
  - cert-manager
  - cloudflare-ddns
  # - datadog
  - default
  - external-dns
  - flux-system
  - ingress-nginx
  - kubernetes-dashboard
  - monitoring
  - satisfactory
  - vault
