---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc
  - argo
  # - atlantis
  - cloudnative-pg
  # - csgo
  - default
  - descheduler
  - dump.yaml
  # - falco
  - jellyfin.yaml
  - k6
  # - minecraft
  - nix-cache.yaml
  # - postgres
  - redis
  - reloader
  - rosie
  - satisfactory
  - vault
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /spec/interval
        value: 5m0s
      - op: replace
        path: /spec/chart/spec/interval
        value: 10m0s
      - op: replace
        path: /spec/maxHistory
        value: 2
      - op: replace
        path: /spec/upgrade
        value: { cleanupOnFail: true, remediation: { retries: 5 } }
