apiVersion: v1
kind: Secret
metadata:
    name: nix-serve
    namespace: nix-kache
stringData:
    NIX_SERVE_KEY: ENC[AES256_GCM,data:MrvdNFSe5PmCGRIDmwkNOBoPb1UInp+SNj267sJ8Fh/TNF39I84wB/Mfy9TdGhNvQGd42MNwN+79gFht88uRPIquT35RW56n4dl4SlNEE0pFNfTjZMMxBUvQ8vLym5hvJCg=,iv:2rm/VoaFr/VFTYdPAOn5rYeHNhYVeLwsyKcRvPWOFU8=,tag:nGb9qUhf1no5MJrr8KT6fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWEdtMXQzNExXZzd1Y1Nu
            QU5CMFBhOHZ2UmdOdklkOEhqci9OSjJtSFdZClA2KzJ4b25lazVnRDNvc2xjaEp5
            UUI4SVRDM3ZtWjlMNHExYy9SNFlLM1UKLS0tIEpXeC9aelJDQi91NXczQmFIWEVP
            TTgwZnJkVmJwdy9xQ0lFSzZyUUxUeTQKRoNlhWA1PCYfvBmfU4IMVUp4Z723wBJt
            Z4l2hluReccxmooy9dIfeMdE3/qW/JYmJ0W49qUfEP1asYv7I8FyYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T04:34:01Z"
    mac: ENC[AES256_GCM,data:btt658Q4wJJl65jym3uHEiEAUu190SkJ153kFf+uo2uI6QQ3tqSflORpUNb1DTZJtU2jPGq9IANbYYUrMAawxuKcqkh0X4+pY+WJbvkbgXI/TTz4I3G+NWbhEyLsHmrmhJvpZKYHZsiuHK8y2fWn8TO8Bkea9EOZIoZ7rldOlkE=,iv:hXtkyXiSti8P73+wIn0qdfwAeUqknc+/um5WEsEtPcc=,tag:wOS0IM96slBWvrk+Dqu6gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
