---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spindrift-policy
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/base/platform/spindrift-policy
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: kyverno
  wait: true
