---
apiVersion: v1
kind: Namespace
metadata:
  name: arc
  labels:
    kustomize.toolkit.fluxcd.io/prune: enabled
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    # pod-security.kubernetes.io/enforce: privileged
    # pod-security.kubernetes.io/enforce-version: latest
