{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kthx-engine.serviceAccountName" . }}
  namespace: {{ include "kthx-engine.namespace" . }}
  labels:
    {{- include "kthx-engine.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
