{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spindrift.serviceAccountName" . }}
  namespace: {{ include "spindrift.namespace" . }}
  labels:
    {{- include "spindrift.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
