---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - external-dns.yaml
  - hajimari.yaml
  - ingress-nginx.yaml
  - k8s-at-home.yaml
  - metallb.yaml
  - metrics-server.yaml
