---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - assemblyline.yaml
  - cilium.yaml
  # - datadog.yaml
  - external-dns.yaml
  - grafana.yaml
  - hajimari.yaml
  - hashicorp.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - k8s-at-home.yaml
  - kubernetes-dashboard.yaml
  - loki.yaml
  # - longhorn.yaml
  - metallb.yaml
  - metrics-server.yaml
  - prometheus.yaml
