---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/metallb/metallb
  ref:
    # renovate: datasource=github-releases depName=metallb/metallb
    tag: "v0.13.7"
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/metallb/charts
