---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: arc
spec:
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
