---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system
  values:
    driver:
      kind: modern-bpf
    collectors:
      kubernetes:
        enabled: true
    customRules:
      rules-allow-runc-memfd.yaml: |-
        # https://github.com/falcosecurity/falco/issues/3444
        # Add runc to known binaries
        - list: known_memfd_execution_binaries
          items: [runc, .runc-wrapped]
          override:
            items: append

        # Add specific path conditions to existing macro
        - macro: known_memfd_execution_processes
          condition: or (proc.exepath = "memfd:runc_cloned:/proc/self/exe") or (proc.exe = "memfd:runc_cloned:/proc/self/exe")
          override:
            condition: append
        
        # k8s containers that talk to the apiserver
        - macro: k8s_containers
          condition: or (container.image.repository in (docker.io/kiwigrid/k8s-sidecar, quay.io/kiwigrid/k8s-sidecar))
          override:
            condition: append
    falco:
      grpc:
        enabled: true
      grpc_output:
        enabled: true
    serviceMonitor:
      create: true
    tolerations:
      - effect: NoSchedule
        key: unschedulable
        operator: Equal
        value: "true"
    falcosidekick:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRules:
        enabled: true
      grafana:
        dashboards:
          enabled: true
          configMaps:
            falcosidekick:
              namespace: monitoring
      config:
        loki:
          hostport: http://loki.monitoring.svc.cluster.local:3100          
          tenant_id: "1"
          grafanaDashboard:
            enabled: true
            namespace: monitoring
      webui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ${CERT_CLUSTER_ISSUER}
            hajimari.io/enable: "true"
            hajimari.io/icon: "mdi:bird"
          hosts:
            - host: &host "falco.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: *host
