---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  interval: 24h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 41.7.4
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    cleanPrometheusOperatorObjectNames: true
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 25Gi
    grafana:
      adminPassword: ${GRAFANA_ADMIN_PASSWORD}
      additionalDatasources:
        - name: Loki
          type: loki
          isDefault: false
          access: proxy
          url: http://loki:3100
          version: 1
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - &grafana grafana.${SECRET_DOMAIN}
        tls:
          - secretName: *grafana
            hosts:
              - *grafana
    alertmanager:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - &am am.${SECRET_DOMAIN}
        tls:
          - secretName: *am
            hosts:
              - *am
