---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: monitoring
spec:
  interval: 24h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 43.1.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    defaultRules:
      rules:
        etcd: false
        kubeControllerManager: false
        kubeProxy: false
        kubeSchedulerAlerting: false
    cleanPrometheusOperatorObjectNames: true
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 25Gi
    grafana:
      adminPassword: ${GRAFANA_ADMIN_PASSWORD}
      deleteDatasources:
        - name: Loki
          orgId: 1
      additionalDataSources:
        - name: Loki
          type: loki
          isDefault: false
          access: proxy
          url: https://loki.lolwtf.ca
          orgId: 1
          version: 1
          jsonData:
            httpHeaderName1: "X-Scope-OrgID"
          secureJsonData:
            httpHeaderValue1: "1"
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - &grafana grafana.${SECRET_DOMAIN}
        tls:
          - secretName: *grafana
            hosts:
              - *grafana
    alertmanager:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - &am am.${SECRET_DOMAIN}
        tls:
          - secretName: *am
            hosts:
              - *am
