apiVersion: v1
kind: Secret
metadata:
    name: gateway-ssh
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:3W6OAORpj6zLGt5BObGI2i25cA==,iv:9Kep+5jMQa6YfDvcG4FFXS8u4VOc6XKYw70QNNPJDQ4=,tag:9wyYb88fni/razsCs4LdFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmODNjOFlyNVlzSE5OSFhV
            MlhVNWFwckhlcldCNWdkYlJ0emUrN3F4K3lnCmw3ZTJGSURhZEEyNVdlaFBqMHU1
            WFM4cmRzL1pqeDBIN1FJQTZNKzJMaUUKLS0tIHZoeUR6RmQxYlovUHJGYmtFcm1a
            Y1BIS20xYjIyMk50V1RoRFZYbjU3VHcKdn1uEXKR50pWgoTAggGCE/SNWPHz/d7/
            VgXQm9chkW5vA9NMaLqOAZhG6nRhw3O/aiFrtZpLovFW2FjE/GIGVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T20:41:48Z"
    mac: ENC[AES256_GCM,data:sx233DIjy6D8oc/x6W5OIup0ysfWpyc52VuffOZY+rGFlHluiFi0VwNQx8TmWtxRYe9bzQd+usyb6HRqdfjHburdoZN+WAn6YDkFRZvYPJ8Ly8LMbvQYZo7AiSfKKgqdg2efSMrMNrHirdNxyLoK7m8Wm1woqOWE022c/3bmwok=,iv:vfvsLVjRHmB24iH4KXf9mo5Cr48dNipaa0hcHu6u/uo=,tag:iIGIggUIYqtvP7AbCUvxGA==,type:str]
    version: 3.13.3
