apiVersion: v1
kind: Secret
metadata:
    name: gateway-ssh
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:MZD3ffFu/7E=,iv:YwnhoKAqPAyJBXOR7QdI/zlgCTU4Ijotrq/zKiFaYAA=,tag:dcaYjsX/nJqSiQBo3AOjxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmODNjOFlyNVlzSE5OSFhV
            MlhVNWFwckhlcldCNWdkYlJ0emUrN3F4K3lnCmw3ZTJGSURhZEEyNVdlaFBqMHU1
            WFM4cmRzL1pqeDBIN1FJQTZNKzJMaUUKLS0tIHZoeUR6RmQxYlovUHJGYmtFcm1a
            Y1BIS20xYjIyMk50V1RoRFZYbjU3VHcKdn1uEXKR50pWgoTAggGCE/SNWPHz/d7/
            VgXQm9chkW5vA9NMaLqOAZhG6nRhw3O/aiFrtZpLovFW2FjE/GIGVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T20:19:20Z"
    mac: ENC[AES256_GCM,data:A+5lM+5A05HXgd/T3Q5an6VWKNNdELvS8gI6F5X6LwRl/wbaGa0xG6hqf2qN5oILat0/wgupcCBKAUClDbsuHjrxvcFoohAc6dApvzJwTBYiJAI5tSLVuquZlfFAGaFUBhZnbRNdHhQzU0KS8yJIoYG6PrsV0Ni+5+ydnuf+mRQ=,iv:n+2Jvmf7wwDgaBp5kBjbzzK07orh9FjpOIBBBdp/1i0=,tag:0Lqmk+iyf256OytMifqbQQ==,type:str]
    version: 3.13.3
