tunnel: lab
credentials-file: /etc/cloudflared/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
- hostname: cf.lolwtf.ca
  service: http://request-headers.request-headers:8080
- hostname: cf2.lolwtf.ca
  service: http://request-headers-gitops.request-headers-gitops:8080
- hostname: request-headers-gitops.lolwtf.ca
  service: http://request-headers-gitops.request-headers-gitops:8080
- service: http_status:404
# - hostname: wishin.lolwtf.ca
#   service: http://wishin.wishin:8080
