name: nix
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/nix-ci.yaml
      - flake.lock
      - "**/*.nix"
  pull_request:
    paths:
      - .github/workflows/nix-ci.yaml
      - flake.lock
      - "**/*.nix"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@92148bb48b9a0c5458c53dd0b368fbfbfbaa3210 # main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: DeterminateSystems/flake-checker-action@2e32b6dce651e6992cc110d569e0b60746e31b48 # main
      - run: nix flake check
  nixos:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@92148bb48b9a0c5458c53dd0b368fbfbfbaa3210 # main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: jonpulsifer
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}
      - run: nix build .#nixosConfigurations.optiplex.config.system.build.toplevel
