name: nix-rpi-sd
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to build'
        required: true
        default: 'cloudpi4'
        type: choice
        options:
          - iso
          - cloudpi4
          - homepi4
          - screenpi4
          - wsl
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ${{ contains(inputs.image, 'pi4') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix flake check
  nixos:
    runs-on: ${{ contains(inputs.image, 'pi4') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    needs: check
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: cachix/cachix-action@v16
        with:
          name: jonpulsifer
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}
      - run: nix build .#${{ inputs.image }}
      - uses: actions/upload-artifact@v5
        if: ${{ contains(inputs.image, 'pi4') }}
        with:
          name: ${{ inputs.image }}-sd-image
          path: result/sd-image/nixos-image-sd-card-*
          retention-days: 1
          compression-level: 0
      - uses: actions/upload-artifact@v5
        if: ${{ inputs.image == 'iso' }}
        with:
          name: nixos-iso
          path: result/iso/nixos-*
          retention-days: 1
          compression-level: 0
