name: nix
on:
  push:
    paths:
      - .github/workflows/nix.yaml
      - flake.lock
      - "**/*.nix"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix flake check
  nixos:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: cachix/cachix-action@v16
        with:
          name: jonpulsifer
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}
      - run: nix build .#nixosConfigurations.optiplex.config.system.build.toplevel
