name: 'Terraform CI'
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  validate:
    name: 'fmt, init, validate'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules:
        - cloudflare
        - gcp/organization
        - unifi
        - vault
        - workspace
    defaults:
      run:
        working-directory: ${{ matrix.modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init -backend=false
      - name: Terraform Validate
        id: validate
        run: terraform validate
