apiVersion: v1
kind: Secret
metadata:
    name: spindrift-env
    namespace: spindrift
type: Opaque
stringData:
    SPINDRIFT_ENROLMENT_TOKEN: ENC[AES256_GCM,data:7waL0a1UjOWO3FZ4ETkdbY2op0fUcrwBlnlI/Ryfhbk0erI9HkebAUrHpw==,iv:PrdKSR6nyYZqz3tUEguVEXzZwoRtzalfOu/BJlxhg5A=,tag:BegMo+jgS2BsVuDos553Mw==,type:str]
    SPINDRIFT_CREDENTIAL_KEYRING: ENC[AES256_GCM,data:C5QT+VjbKLlK17+VrTa57k+CNlTwPd5iAkCclbDuRhSU0YzIYtHB/fYEl7T9Z6JyJn6amgA39W1uDhrlSLFkjZZ2pZwzpTOMCzL8,iv:h1ondPCwwmJULLMABwC2iRuFi961bs6GQjDuPbMc6/s=,tag:pJsROp/JSDdwjDWhWpJRvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOEk0djFKaU9ReThralZa
            ekM2V2NKZlprVWtFMmxjSU54MTkzYTJkcG5FCmNMWWpoQytKNm96WmJhYkg2YTFo
            MXBVZkJyNGNxdEhtcE5rblpFRmo2ZEUKLS0tIG9jbmF2MjJwV3RMQjN2SUw2R1hx
            cDBFVGc4ZXVkTVo3Z0orOHROdlpoRG8Kn99OMwpTyotkEFSBC//kHulCNyJHBdGf
            K9OZIvhjhLX9Y/lWE6flkUa7lC2tIfP9SSvSgbxJi3B0FftrN6sG3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T11:08:59Z"
    mac: ENC[AES256_GCM,data:Ou5/1lvVo4ZBVAZXIzrirSJMrlD8Wi5KKXDRZfDy3mc3JZPNaPnr0/kYrJYvly4qtialuXdCABOCoknYNp6U+VtCXbIO8eaDZ29lc/EImKnK8tvKLkVP38+o+zZed0LmWtq9kU2Ix8Va+RGnKzlDRz9rVWHeJVlhQJb7nyvoYPI=,iv:kp5vckmWYE8fhT5iz6945kxG5EXLkhmkq/RGeBRugI4=,tag:POh2V3J3d/CTaQ3p/aqOpA==,type:str]
    version: 3.13.3
