apiVersion: v1
kind: Secret
metadata:
    name: spindrift-env
    namespace: spindrift
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uAb+SuLLyH1ky/j7CBITdgY303LOcHaU/1Bh11NAGoXFh1WgIbXwykP6iUUN7cVeGrNXJpy4JUGado/xuCp4+RAvYSlNJeXAc0MaAymP,iv:4TS4oVMzqJpDXdzZqfxnz06Zxc/RtFhSKgUcJY0k79M=,tag:wAWOQTipqjZNek80TU9gFw==,type:comment]
    #ENC[AES256_GCM,data:wKQeZcAeTRAHf6gLWG1WDJTGSpxsSfNYilmSMt3DA8iQpKct/Pxoe84JMmfJp7IBQ5QOfbHnhX1F6k685v9K1dliuUnHnhWQWQ==,iv:fz7Dmp341H3+KAH7xfRhB4m9Ov4HOecSjE/t5zBNHeg=,tag:8SM9OnMT3OFO8W2Ydmu2ng==,type:comment]
    #ENC[AES256_GCM,data:iENp88W2iq7sgJrMV5BTZHh+nuE8qtLknyTArYmeEPJMZOAe150f5ZYDRf8QwuHtWwaMxSuchX3V1OQ8QJcEpnuzSyIWtFawRlF1yDO/Vg==,iv:IorC46BKrUHtc78Zox4wZZdwRKTeMV5ggJGvCIi0Atk=,tag:Q1C13EGTH3nY4N9Rb2k6IA==,type:comment]
    #ENC[AES256_GCM,data:t/B+beSJUfuw1iAQFJS58TVGpLi8vrSXydfhYj4zvvrJqTd8dC1eaU0mitcKOOes2YNQZ2dac6U9YSRWBJc0krQZTpA5fYT36ZeYhw==,iv:zDQbkZ1SQLYNEssjXcKma5A3NgQz61CLjpGBJG9SY8Q=,tag:tYA5vkga1y6IX7IbbC27+w==,type:comment]
    #ENC[AES256_GCM,data:unAkSE7lzxAfOJR0Gb9BHk+9oXH2UOOtLSDPUezCft5jh1aF87Mi5nRAPadgJj9OkAUVEYjPPf+KXIUPDcLpROMQR7WPzyHgP1FK,iv:4THmbJ9OPKs84cNQRhdXANs8AI2H6YR06rBR397gjic=,tag:N7kwoZjcBiADAyEC3eI5Kw==,type:comment]
    SPINDRIFT_MANIFEST: ENC[AES256_GCM,data:TXB4BBengES5eEX+UN+aUJUJVemOs7sgoW1YN5z5pQeXlBMqOrcDQR3hVsgAELrAIaXGtooBTJ9e6gUnX5c7wCW0ISEEGInS+v8GwGm95HbCbzJvuLkmmbFHlY6x5kBif54fDxHbPWRXBOR1ijGr7hkwMxtw6DHxZX+QD5xNkKsdW/PS9FHiLBrEpKS5nrPQbQMaIWNQj2yKLjLKE6BZwgOpIbfYo8PF9c9SFsXHs0ccHGgHYjGYGcVGCpBXfCgqVDdhinqRXM4KO0fo+CoRGhLa9D7knMDNM/3/u94LoNctalmmkgTixhXVlBTbh5Gmkn5spJ9+dUqNmWqa4osnQWuHwllU7lIOUSeL0lxuTcyKpOffj9WQrIpz9WwqUj/tA+yN4w6AXv0UQKucdhDujTAACzmm3Q0WinD8LtL4AVD5CegElxt3RgIU7h6O+l9pi02odjJnyuWR7gXUXYGQwaZ5C7YBKV7Fde+u4SlZj/5bIz19S+4G7hAEVnV86eYZk5MvE+gsdw5lXnAHydCwiv7vaRs6eejkm2VI8JIhTezeEENNcffBijUCrFvmQzqJpxZMxQYHqCVRP3dXjnl2KxsGeWE8ljwQGVB0FDy3Cl/qO9gzh/Z7WEX0WqwR76LBdh9K1TuvmkLs7AhagafDRrqsro981BIOtSVO1E/B1O5YBTcYoeS3HUWv0UG7aBBGo/yH31yoiIJ3rgipbS6KjygYSbTGOaP3aOR1HeDJXTqSyOTGGem/IBZEPdz5VHDQfPTIN2OULpCby8S+igYwBv6nnRDuQKtO7WBrQKXILGcg6mf4lMgIDKEQCXgWSJx0O+Wc0g0gzvGV49DclthkKxaAqoJn+xlAZHqLvwx1nWg=,iv:sKMX+WRFR2cxnVymw1wsLjEHNgjbJtffHZp0hS5oOwQ=,tag:vV2PG1ycfPb46EQCSTLNlg==,type:str]
    SPINDRIFT_ENROLMENT_TOKEN: ENC[AES256_GCM,data:YeeLFGjz8vsX5CkudHuMeq4zlEcM7Mug6GdiWHg/rCIW2Up84gRNaPTNH41q3wo+J2R2y4D2BtqHTabJicuJKw==,iv:sViBSOc+aoeA3EfbXvWaQXTPjBkW4jZqes6UasJglr4=,tag:eo0u2YjkBcHpeQIAKcn/FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN1luUWJRb2x4emFHc0o0
            SGJzWkp3TmVhenhaRjByYW44S2kzVlpTWlQ4CmVoOFFKeDFhR2ZqNTZmc0hJMm9K
            MEptK0tkVWVraDcva28xME1tOGVrVncKLS0tIHJnSDY4SldPbDBzUmtwN296bTVE
            SEpZSFBQeEVnVndKczNiZWNaME5teGMKUTLlBs+6Xu6dRICZ5vcgxfppvCy1nAHq
            5QBdFU8hiJXl0TOsVNgBE2Cq1ylu6qwa1s+xE2bF0xEg/yOu4Flciw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T03:47:56Z"
    mac: ENC[AES256_GCM,data:5t1wUO0doUZ/WUaotEzn8ZGKy6qiC8RyEASNkaTr8m48DKKqUlH6LKk+ZQc0pXyPX5EubB/X4wLf4joCRnfB7YSBY23SUBq9PM/W7UpVH/aNycdijp5ru4iP3xdV9klYsnCMLbhq8CcftMHhbTHxPb+7ww0h4ylRmKhvs2NXax8=,iv:XjQEM83E++rsNuQv/kQvbBsU4iKd+NSM16UQXZjFBhY=,tag:gQJ2vsPcvGMChEtPRCo3sw==,type:str]
    version: 3.13.3
