---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spindrift-target-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spindrift-target-discovery
subjects:
  - kind: ServiceAccount
    name: spindrift
    namespace: spindrift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spindrift-target-delivery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spindrift-target-delivery
subjects:
  - kind: ServiceAccount
    name: spindrift
    namespace: spindrift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spindrift-target-chart-artifact
  namespace: spindrift-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spindrift-target-chart-artifact
subjects:
  - kind: ServiceAccount
    name: spindrift
    namespace: spindrift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spindrift-target-dns
  namespace: spindrift-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spindrift-target-dns
subjects:
  - kind: ServiceAccount
    name: spindrift
    namespace: spindrift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spindrift-target-datastores
  namespace: spindrift-datastores
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spindrift-target-datastores
subjects:
  - kind: ServiceAccount
    name: spindrift
    namespace: spindrift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spindrift-target-datastores-legacy
  namespace: spindrift-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spindrift-target-datastores-legacy
subjects:
  - kind: ServiceAccount
    name: spindrift
    namespace: spindrift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spindrift-target-chart-source
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spindrift-target-chart-source
subjects:
  - kind: ServiceAccount
    name: spindrift
    namespace: spindrift
